### ISSUE TITLE
need to ensure RGBA EXR on capture

### ISSUE THREAD

**Issue by spiraloid** [Powerbyte7/seurat_capture_addon#1]
bpy.context.scene.render.image_settings.color_mode = 'RGBA'

otherwise

ERROR: EXR channel "A" missing. Existing channels: B, G, R
Failed loading Image4 file front_color.0000.exr

**Comment by Powerbyte7** [comment]
Hey, thanks for reporting the issue!

With 86f4e49f29b8b717983b787ba3cd45c013167b6e this should be fixed, though I did it a bit differently. Your solution would work too, but in practice Seurat doesn't account for the alpha channel, so I decided it'd be better to remove the alpha channel from the json file instead.

**Comment by Powerbyte7** [comment]
It turns out Seurat does expect four channels for an EXR file, I got it confused. 😅

Changed to your solution with 4da119e3f2bd1a0fdee455b5cf30e9414536af0e
