### ISSUE TITLE
If the MeshOutput folder doesn't exist.  it errors.

### ISSUE THREAD

**Issue by spiraloid** [Powerbyte7/seurat_capture_addon#2]
Generating textures: [+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++] 00:03:10
ERROR: cannot open "C:\tmp\MeshOutput\output.ice" for writing
cannot open "C:\tmp\MeshOutput\output.obj" for writing

**Comment by Powerbyte7** [comment]
Fixed with ae5c491c20a3516df272b359161c653712cfc1e4, thanks!
