### ISSUE TITLE
Can't open directory.

### ISSUE THREAD

**Issue by ghost** [Powerbyte7/seurat_capture_addon#4]
When I try to process the seurat data I get this error message in the console. Any clue on why this might be happening to me?

(EDIT) 
I also tried to change the folder it saves to, but it seems like it still tries to save where the blend file is located anyway.

![image](https://user-images.githubusercontent.com/66656514/109409645-82042e00-7962-11eb-8802-581f3524129e.png)

**Comment by Powerbyte7** [comment]
Hi, thanks for the report!

I think you're using a file with spaces, the code I wrote didn't properly account for them. This should now be fixed with 9c5ca9da4c335ecac05e415d83df0034515bb89d.
