### ISSUE TITLE
Latest version won't install.

### ISSUE THREAD

**Issue by ghost** [Powerbyte7/seurat_capture_addon#5]
Sorry to bother you with another issue, but I can't seem to install the new version of the addon.

I have no problems reinstalling the 1.1.0 version.

![image](https://user-images.githubusercontent.com/66656514/109431771-2ecbc300-79d6-11eb-86b8-65cc6daba1ee.png)

**Comment by Powerbyte7** [comment]
Hey, I let a typo slip through, sorry! >_<
Fixed it with d600926fff736f40452dc7303c793250fec04ecb

I definitely need to up the amount of testing I do.
