### ISSUE TITLE
Install addon no module

### ISSUE THREAD

**Issue by threesixtyat** [Powerbyte7/seurat_capture_addon#7]
Hy i get a:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-2.91.0-windows64\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'seurat_capture_addon-1'

what could this be?

this?

https://developer.blender.org/T57682

thanks @Powerbyte7

**Comment by Powerbyte7** [comment]
@threesixtyat  Hey, it looks like you've installed the ZIP package from Github. You should install the ZIP file provided on Gumroad instead, which is available [here](https://gumroad.com/l/seurat-capture). Let me know if that fixes your problem.
