### ISSUE TITLE
Function.view_layer expected a ViewLayer type, not Depsgraph

### ISSUE THREAD

**Issue by llampwall** [Powerbyte7/seurat_capture_addon#8]
This is what I get when I try to capture. The capture box is not intersecting anything in the scene. Do I need to make an adjustment to the ray_cast() function?

![image](https://user-images.githubusercontent.com/1223942/117258971-6d309480-ae02-11eb-87f8-7146744cff6f.png)

**Comment by llampwall** [comment]
Ok I'm an idiot. I switched to my desktop which apparently was still running 2.82. It runs after upgrading. Gave me a thousand 'GPUTexture: Blender Texture Not Loaded!' errors, but that at least means something to me.

Thanks for making this by the way. Good work.

**Comment by Powerbyte7** [comment]
Okay, closing the issue then :)
